syntax = "proto2" ;

package Geneanet.Geneweb.Api2.Proto.Model;

enum Sex {
  UNKNOWN = 2;
  MALE = 0;
  FEMALE = 1;
}

message Npocc {
  optional string n = 1;
  optional string p = 2;
  optional int32 occ = 3;
}

message BasicInfos {
  optional string lastname = 1;
  optional string firstname = 2;
  optional Sex sex = 3;
  optional string image = 4;
  optional string public_name = 5;
  repeated string aliases = 6;
  repeated string qualifiers = 7;
  repeated string firstname_aliases = 8;
  repeated string surname_aliases = 9;
}

message Request {
  optional int32 index = 1;
  optional Npocc npocc = 2;
  optional PersonRequest person_request = 3;
}

message PersonRequest {
  optional bool index = 1;
  optional bool npocc = 2;
  optional bool basic_infos = 3;
  optional bool parents = 4;
}

message Person {
  optional int32 index = 1;
  optional Npocc npocc = 2;
  optional BasicInfos basic_infos = 3;
  optional Person father = 4;
  optional Person mother = 5;
}
