syntax = "proto2" ;

package Geneanet.Geneweb.Api2.Proto.Model;

enum Sex {
  UNKNOWN = 2;
  MALE = 0;
  FEMALE = 1;
}

message Npocc {
  optional string n = 1;
  optional string p = 2;
  optional int32 occ = 3;
}

message NameAliases {
  repeated string aliases = 2;
  repeated string qualifiers = 3;
  repeated string firstname_aliases = 4;
  repeated string surname_aliases = 5;
}

message Request {
  optional int32 index = 1;
  optional Npocc npocc = 2;
  optional PersonRequest person_request = 3;
}

message PersonRequest {
  optional bool index = 1;
  optional bool npocc = 2;
  optional bool lastname = 3;
  optional bool firstname = 4;
  optional bool public_name = 5;
  optional bool sex = 6;
  optional bool image = 7;
  optional bool name_aliases = 8;
  optional PersonRequest father = 9;
  optional PersonRequest mother = 10;
  optional bool sosa = 11;
}

message Person {
  optional int32 index = 1;
  optional Npocc npocc = 2;
  optional string lastname = 3;
  optional string firstname = 4;
  optional string public_name = 5;
  optional Sex sex = 6;
  optional string image = 7;
  optional NameAliases name_aliases = 8;
  optional Person father = 9;
  optional Person mother = 10;
  optional string sosa = 11;
}
