(env ( _ (flags (:standard -w +a-4-9-30-35-40-42-44-48)) ) )

(alias
  (name plugin)
  (deps (file META) (source_tree assets) plugin_api.cmxs)
)

(copy_files assets/*.proto)

(rule
  (deps api.proto)
  (targets api_protoc.ml api_protoc.mli)
  (action (progn
            (system "mkdir -p protoc_gen")
            (run ocaml-protoc --binary --yojson --ml_out protoc_gen/ api.proto)
            (run mv protoc_gen/api.ml api_protoc.ml)
            (run mv protoc_gen/api.mli api_protoc.mli)
          )
  )
)

(rule
  (deps api_saisie_read.proto)
  (targets api_saisie_read_protoc.ml api_saisie_read_protoc.mli)
  (action (progn
            (system "mkdir -p protoc_gen")
            (run ocaml-protoc --binary --yojson --ml_out protoc_gen/ api_saisie_read.proto)
	    (run mv protoc_gen/api_saisie_read.ml api_saisie_read_protoc.ml)
            (run mv protoc_gen/api_saisie_read.mli api_saisie_read_protoc.mli)
          )
  )
)

(rule
  (deps api_saisie_write.proto)
  (targets api_saisie_write_protoc.ml api_saisie_write_protoc.mli)
  (action (progn
            (system "mkdir -p protoc_gen")
            (run ocaml-protoc --binary --yojson --ml_out protoc_gen/ api_saisie_write.proto)
	    (run mv protoc_gen/api_saisie_write.ml api_saisie_write_protoc.ml)
            (run mv protoc_gen/api_saisie_write.mli api_saisie_write_protoc.mli)
          )
  )
)

(rule
  (deps api_stats.proto)
  (targets api_stats_protoc.ml api_stats_protoc.mli)
  (action (progn
              (system "mkdir -p protoc_gen")
              (run ocaml-protoc --binary --yojson --ml_out protoc_gen/ api_stats.proto)
              (run mv protoc_gen/api_stats.ml api_stats_protoc.ml)
              (run mv protoc_gen/api_stats.mli api_stats_protoc.mli)
          )
  )
)

(library
  (name plugin_api_lib)
  (public_name geneweb_plugin_api.lib)
  (libraries geneweb geneweb.gwd_lib geneweb.util geneweb.caches csv piqirun.ext pbrt yojson pbrt_yojson)
  (modules
    api_saisie_read_protoc
    api_saisie_write_protoc
    api_protoc
    api_stats_protoc
    api
    api_csv
    api_def
    api_graph
    api_marshal_dico
    api_piqi
    api_piqi_util
    api_piqi_ext
    api_saisie_autocomplete
    api_saisie_read
    api_saisie_read_piqi
    api_saisie_read_piqi_ext
    api_saisie_write
    api_saisie_write_piqi
    api_saisie_write_piqi_ext
    api_search
    api_stats
    api_stats_piqi
    api_stats_piqi_ext
    api_update_family
    api_update_person
    api_update_util
    api_util
    api_warnings
  )
  (wrapped true)
  (optional)
)

(executable
  (name plugin_api)
  (libraries
    geneweb
    geneweb.gwd_lib
    geneweb.wserver
    geneweb.caches
    plugin_api_lib
  )
  (embed_in_plugin_libraries geneweb_plugin_api.lib)
  (modes (native plugin))
  (modules plugin_api)
  (optional)
)
